# .github/workflows/build-and-release.yml
name: Build and Release Pico W Firmware

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.1
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Update PlatformIO platforms and libraries
      run: |
        pio pkg update
    
    - name: Build firmware
      run: |
        pio run --environment pico
    
    - name: Get version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: WordClock Pico W Firmware ${{ steps.version.outputs.version }}
        body: |
          Automatic release of WordClock firmware ${{ steps.version.outputs.version }} for Raspberry Pi Pico W
          
          ## Installation via OTA Update
          1. Connect to your WordClock's WiFi setup mode
          2. Go to the configuration page in your browser
          3. Click "Check for Updates"
          4. Click "Install Update" when available
          5. Wait for the LED progress bar and automatic restart
          
          ## Manual Installation
          1. Download the .uf2 file below
          2. Hold BOOTSEL button while plugging in your Pico W
          3. Drag the .uf2 file to the RPI-RP2 drive
          4. The Pico W will automatically restart with new firmware
          
          ## Changes
          - See commit history for detailed changes
          - Version comparison available in the WordClock web interface
        draft: false
        prerelease: false
    
    - name: Upload UF2 firmware
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .pio/build/pico/firmware.uf2
        asset_name: wordclock-pico-w-${{ steps.version.outputs.version }}.uf2
        asset_content_type: application/octet-stream
    
    - name: Upload BIN firmware (for OTA)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .pio/build/pico/firmware.bin
        asset_name: wordclock-pico-w-${{ steps.version.outputs.version }}.bin
        asset_content_type: application/octet-stream
